import { readFile, writeFile, pathExists } from 'fs-extra';
import path from 'path';
import chalk from 'chalk';

export async function mergeSchema(targetDir: string, componentName: string) {
	const schemaDir = path.join(targetDir, 'src/lib/server/schema');
	const mainSchemaPath = path.join(schemaDir, 'index.ts');
	const componentSchemaPath = path.join(schemaDir, `${componentName}.ts`);

	// Check if component schema was added
	if (!(await pathExists(componentSchemaPath))) {
		return;
	}

	// Read main schema file
	let mainSchema = '';
	if (await pathExists(mainSchemaPath)) {
		mainSchema = await readFile(mainSchemaPath, 'utf-8');
	} else {
		// Create base schema file
		mainSchema = `/**
 * Combined database schema
 * Auto-generated by Brixkit CLI
 */

export const schema = {};
`;
	}

	// Check if component is already exported
	const exportPattern = new RegExp(`export \\* from '\\.\\/${componentName}\\.ts'`);
	if (exportPattern.test(mainSchema)) {
		console.log(chalk.yellow(`  Schema for ${componentName} already exported`));
		return;
	}

	// Add export for the new component schema
	const lines = mainSchema.split('\n');
	const exportIndex = lines.findIndex((line) => line.includes('export const schema'));

	if (exportIndex === -1) {
		// No schema export found, add at the end
		lines.push(`export * from './${componentName}.ts';`);
	} else {
		// Insert before schema export
		lines.splice(exportIndex, 0, `export * from './${componentName}.ts';`);
	}

	// Update the schema object to include new component
	const schemaObjIndex = lines.findIndex((line) => line.includes('export const schema'));
	if (schemaObjIndex !== -1) {
		// Find the schema object definition
		const importStatement = `import * as ${componentName}Schema from './${componentName}.ts';`;

		// Add import if not exists
		if (!mainSchema.includes(importStatement)) {
			lines.splice(schemaObjIndex, 0, importStatement);
		}

		// Update schema object
		const schemaLine = lines.findIndex((line) => line.includes('export const schema'));
		if (schemaLine !== -1 && lines[schemaLine].includes('{}')) {
			// Empty schema, replace
			lines[schemaLine] = `export const schema = {\n\t...${componentName}Schema\n};`;
		} else if (schemaLine !== -1) {
			// Existing schema, need to merge
			// This is simplified - a real implementation would parse the AST
			const currentSchema = lines[schemaLine];
			if (currentSchema.includes('};')) {
				lines[schemaLine] = currentSchema.replace('};', `,\n\t...${componentName}Schema\n};`);
			}
		}
	}

	await writeFile(mainSchemaPath, lines.join('\n'), 'utf-8');
	console.log(chalk.green(`  Merged schema for ${componentName}`));
}
